import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";
import { packageRootEnvPath } from "./dotenv-path.js";
import { AgentError, ConfigError } from "./errors.js";

export interface BootstrapStartOptions {
  agentName: string;
  mode?: "create" | "connect";
  agentAddress?: string;
  keyName?: string;
  dailyLimit?: string;
  monthlyLimit?: string;
  perTransactionLimit?: string;
  autoTopup?: boolean;
  apiUrl?: string;
  envPath?: string;
  network?: string;
}

export interface BootstrapFinishOptions {
  pollInterval?: number;
  timeout?: number;
  envPath?: string;
  apiUrl?: string;
  force?: boolean;
}

/** Finished bootstrap — approval resolved, .env written with agent credentials. */
export interface BootstrapCompleteResult {
  status: "complete";
  agentKeyAddress: string;
  agentAccount: string;
  envPath: string;
}

/** Start-only: approval requested, user must approve in dashboard, then run `finish`. */
export interface BootstrapPendingResult {
  status: "pending_approval";
  token: string;
  userApproveUrl: string;
  agentKeyAddress: string;
  envPath: string;
  message: string;
}

export type BootstrapResult = BootstrapCompleteResult | BootstrapPendingResult;

const HEX_KEY_RE = /^0x[0-9a-fA-F]{64}$/;
const HEX_ADDR_RE = /^0x[0-9a-fA-F]{40}$/;

function defaultEnvPath(): string {
  return packageRootEnvPath();
}

/** Parse a minimal .env file (KEY=value, # comments, quoted values). */
export function parseDotEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

async function atomicWrite(filePath: string, content: string): Promise<void> {
  const tmpPath = `${filePath}.tmp`;
  await fs.promises.writeFile(tmpPath, content, "utf-8");
  await fs.promises.rename(tmpPath, filePath);
}

function log(message: string): void {
  process.stderr.write(`${message}\n`);
}

function buildEnvContent(vars: Record<string, string>): string {
  const lines: string[] = [
    "# Generated by ampersend-hermes bootstrap",
    `# ${new Date().toISOString()}`,
    "",
  ];

  for (const [key, value] of Object.entries(vars)) {
    lines.push(`${key}=${value}`);
  }

  lines.push("");
  lines.push("# Optional overrides (uncomment to customize):");
  lines.push("# AMPERSEND_API_URL=https://api.ampersend.ai");
  lines.push("# AMPERSEND_NETWORK=base");
  lines.push("# AMPERSEND_MCP_PROXY_PORT=3000");
  lines.push("# HERMES_CONFIG_DIR=~/.hermes");
  lines.push("");

  return lines.join("\n");
}

function buildStubEnvContent(params: {
  agentName: string;
  agentKeyAddress: string;
  agentKey: string;
  token: string;
  apiUrl: string;
}): string {
  return [
    "# ampersend-hermes — approval requested",
    `# Agent name: ${params.agentName}`,
    `# Agent key address: ${params.agentKeyAddress}`,
    `# Approval token: ${params.token}`,
    "#",
    "# After you approve in the ampersend dashboard, run:",
    "#   pnpm bootstrap finish",
    "#",
    `AMPERSEND_AGENT_KEY=${params.agentKey}`,
    `AMPERSEND_API_URL=${params.apiUrl}`,
    "",
  ].join("\n");
}

/**
 * Phase 1 — Generate an agent key, request approval via the ampersend API,
 * and write a stub .env. The user approves in the dashboard, then runs `finish`.
 *
 * Uses `npx ampersend setup start` under the hood.
 */
export async function bootstrapStart(
  options: BootstrapStartOptions,
): Promise<BootstrapPendingResult> {
  const apiUrl = options.apiUrl ?? "https://api.ampersend.ai";
  const envPath = options.envPath ?? defaultEnvPath();

  log(`Requesting agent setup for "${options.agentName}"...`);

  const { execSync } = await import("node:child_process");

  const args = ["ampersend", "setup", "start", "--name", options.agentName, "--force"];

  if (options.mode === "connect") {
    args.push("--mode", "connect");
    if (options.agentAddress) {
      args.push("--agent", options.agentAddress);
    }
  }

  if (options.keyName) args.push("--key-name", options.keyName);
  if (options.dailyLimit) args.push("--daily-limit", options.dailyLimit);
  if (options.monthlyLimit) args.push("--monthly-limit", options.monthlyLimit);
  if (options.perTransactionLimit) args.push("--per-transaction-limit", options.perTransactionLimit);
  if (options.autoTopup) args.push("--auto-topup");

  const env: Record<string, string> = {
    ...process.env as Record<string, string>,
  };
  if (apiUrl !== "https://api.ampersend.ai") {
    env.AMPERSEND_API_URL = apiUrl;
  }
  if (options.network) {
    env.AMPERSEND_NETWORK = options.network;
  }

  let rawOutput: string;
  try {
    rawOutput = execSync(["npx", "-y", ...args].join(" "), {
      encoding: "utf-8",
      env,
      timeout: 30_000,
    }).trim();
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new AgentError("SETUP_START_FAILED", `ampersend setup start failed: ${msg}`);
  }

  let result: { ok: boolean; data?: Record<string, string>; error?: Record<string, string> };
  try {
    result = JSON.parse(rawOutput);
  } catch {
    throw new AgentError("SETUP_START_FAILED", `Unexpected output from ampersend CLI: ${rawOutput}`);
  }

  if (!result.ok || !result.data) {
    const errMsg = result.error?.message ?? "Unknown error";
    throw new AgentError("SETUP_START_FAILED", errMsg);
  }

  const { token, user_approve_url, agentKeyAddress } = result.data;

  // Read the generated agent key from ampersend config
  const ampersendConfigPath = path.join(
    (await import("node:os")).homedir(),
    ".ampersend",
    "config.json",
  );
  let agentKey = "";
  if (fs.existsSync(ampersendConfigPath)) {
    try {
      const ampersendConfig = JSON.parse(
        await fs.promises.readFile(ampersendConfigPath, "utf-8"),
      );
      agentKey = ampersendConfig.pendingApproval?.agentKey ?? "";
    } catch {
      // Ignore parse errors
    }
  }

  // Write stub .env
  if (fs.existsSync(envPath)) {
    const backupPath = `${envPath}.bak.${Date.now()}`;
    await fs.promises.copyFile(envPath, backupPath);
    log(`Backed up existing file to ${backupPath}`);
  }

  const stub = buildStubEnvContent({
    agentName: options.agentName,
    agentKeyAddress,
    agentKey,
    token,
    apiUrl,
  });
  await atomicWrite(envPath, stub);

  const approveUrl = user_approve_url;
  const message =
    `Approval requested. Have the user visit:\n  ${approveUrl}\n\nThen run: pnpm bootstrap finish`;

  log("");
  log(message);
  log("");

  return {
    status: "pending_approval",
    token,
    userApproveUrl: approveUrl,
    agentKeyAddress,
    envPath,
    message,
  };
}

/**
 * Phase 2 — Poll for approval and write the final .env with agent credentials.
 * Uses `npx ampersend setup finish` under the hood.
 */
export async function bootstrapFinish(
  options: BootstrapFinishOptions = {},
): Promise<BootstrapCompleteResult> {
  const envPath = options.envPath ?? defaultEnvPath();
  const pollInterval = options.pollInterval ?? 5;
  const timeout = options.timeout ?? 600;

  log("Polling for approval...");

  const { execSync } = await import("node:child_process");

  const args = [
    "npx", "-y", "ampersend", "setup", "finish",
    "--poll-interval", String(pollInterval),
    "--timeout", String(timeout),
  ];
  if (options.force) args.push("--force");

  const env: Record<string, string> = {
    ...process.env as Record<string, string>,
  };
  if (options.apiUrl) {
    env.AMPERSEND_API_URL = options.apiUrl;
  }

  let rawOutput: string;
  try {
    rawOutput = execSync(args.join(" "), {
      encoding: "utf-8",
      env,
      timeout: (timeout + 30) * 1000,
    }).trim();
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new AgentError("SETUP_FINISH_FAILED", `ampersend setup finish failed: ${msg}`);
  }

  let result: { ok: boolean; data?: Record<string, string>; error?: Record<string, string> };
  try {
    result = JSON.parse(rawOutput);
  } catch {
    throw new AgentError("SETUP_FINISH_FAILED", `Unexpected output: ${rawOutput}`);
  }

  if (!result.ok || !result.data) {
    const errMsg = result.error?.message ?? "Unknown error";
    throw new AgentError("SETUP_FINISH_FAILED", errMsg);
  }

  const { agentKeyAddress, agentAccount } = result.data;

  // Read the now-active agent key from ampersend config
  const ampersendConfigPath = path.join(
    (await import("node:os")).homedir(),
    ".ampersend",
    "config.json",
  );
  let agentKey = "";
  if (fs.existsSync(ampersendConfigPath)) {
    try {
      const ampersendConfig = JSON.parse(
        await fs.promises.readFile(ampersendConfigPath, "utf-8"),
      );
      agentKey = ampersendConfig.agentKey ?? "";
    } catch {
      // Ignore parse errors
    }
  }

  // Also try reading from existing .env stub
  if (!agentKey && fs.existsSync(envPath)) {
    const raw = await fs.promises.readFile(envPath, "utf-8");
    const parsed = parseDotEnv(raw);
    if (parsed.AMPERSEND_AGENT_KEY && HEX_KEY_RE.test(parsed.AMPERSEND_AGENT_KEY)) {
      agentKey = parsed.AMPERSEND_AGENT_KEY;
    }
  }

  if (!agentKey) {
    throw new AgentError(
      "KEY_NOT_FOUND",
      "Agent approved but could not locate the agent key. Check ~/.ampersend/config.json.",
    );
  }

  // Resolve API URL from existing .env or default
  let apiUrl = options.apiUrl ?? "https://api.ampersend.ai";
  if (fs.existsSync(envPath)) {
    const raw = await fs.promises.readFile(envPath, "utf-8");
    const parsed = parseDotEnv(raw);
    if (parsed.AMPERSEND_API_URL) apiUrl = parsed.AMPERSEND_API_URL;
  }

  // Write final .env
  const envVars: Record<string, string> = {
    AMPERSEND_AGENT_KEY: agentKey,
    AMPERSEND_AGENT_ACCOUNT: agentAccount,
  };
  if (apiUrl !== "https://api.ampersend.ai") {
    envVars.AMPERSEND_API_URL = apiUrl;
  }

  await atomicWrite(envPath, buildEnvContent(envVars));
  log(`Wrote ${envPath} — you're ready to go.`);
  log(`Agent: ${agentKeyAddress} → ${agentAccount}`);

  return {
    status: "complete",
    agentKeyAddress,
    agentAccount,
    envPath,
  };
}

export function isBootstrapComplete(
  r: BootstrapResult,
): r is BootstrapCompleteResult {
  return r.status === "complete";
}
